### ISSUE TITLE
Add support for vial macros

### ISSUE THREAD

**Issue by nobodywasishere** [sago35/tinygo-keyboard#38]
I have a fork of this repo with a custom macropad implemented [here](https://github.com/nobodywasishere/mmp/tree/main/firmware/targets/mmp). Attempting to save a macro with vial gives an error "failed to communicate with the device" - don't know if this is an issue with Vial or how this project implements support. Any help would be appreciated.

![image](https://github.com/sago35/tinygo-keyboard/assets/32797552/470d03f8-35f4-436e-86ff-e2944162e347)

**Comment by nobodywasishere** [comment]
Weirdly enough, refreshing the board after this makes one of the keys have `Meh` assigned to it

![image](https://github.com/sago35/tinygo-keyboard/assets/32797552/63f8241e-f1e5-49ff-ac9e-a3bd00be75de)

**Comment by sago35** [comment]
@nobodywasishere 
Thanks for trying tinygo-keyboard.

tinygo-keyboard does not support macro at this time.

I have never used Vial's macro feature before.
However, it looks like an interesting feature and I will try to implement it.
https://get.vial.today/manual/macros.html

**Comment by sago35** [comment]
@nobodywasishere 
I tried implementing Vial macros in #40 
Please give it a try.

**Comment by nobodywasishere** [comment]
That works great! Thank you so much!

**Comment by sago35** [comment]
merged.
